"Build Automation":
- changed-files:
  - any-glob-to-any-file: ['.github/**', '.azuredevops/**']

"Samples":
- changed-files:
  - any-glob-to-any-file: ['samples/**']

"Specs":
- changed-files:
  - any-glob-to-any-file: ['specs/**']

"Documentation":
- changed-files:
  - any-glob-to-any-file: ['docs/**']
